# Generated by Django 4.2 on 2023-04-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Título do emblema')),
                ('badgeIMG', models.ImageField(blank=True, upload_to='badge/', verbose_name='Badge')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='badgeIMG',
        ),
    ]
