# Generated by Django 4.1.7 on 2023-04-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Biografia'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de aniversário'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='perfilIMG',
            field=models.ImageField(blank=True, upload_to='perfil/', verbose_name='Imagem do perfil'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username_personal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nome de Usuário'),
        ),
    ]
