# Generated by Django 4.1.7 on 2023-04-03 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_bio_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username_personal',
        ),
    ]
