# Generated by Django 4.2 on 2023-04-07 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='badge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='badge', to='users.badgeuser'),
        ),
    ]
