# Generated by Django 4.2 on 2023-04-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userbadge_remove_customuser_badge_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBadge',
        ),
        migrations.AddField(
            model_name='customuser',
            name='badgeIMG',
            field=models.ImageField(blank=True, upload_to='badge/', verbose_name='Badge'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='badgeTITLE',
            field=models.CharField(blank=True, default='Novo aqui :)', max_length=20, verbose_name='Título do emblema'),
        ),
    ]
