# Generated by Django 4.2 on 2023-04-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_userbadge_customuser_badgeimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='badgeTITLE',
            field=models.CharField(blank=True, default='Novo aqui :)', max_length=50, verbose_name='Título do emblema'),
        ),
    ]
