# Generated by Django 4.2 on 2023-04-07 10:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('texto', models.TextField(blank=True, verbose_name='Texto')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.CharField(blank=True, max_length=400, verbose_name='Descrição')),
                ('position', models.IntegerField(blank=True, default=0, verbose_name='Posição')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(verbose_name='Comentário')),
            ],
        ),
    ]
