# Generated by Django 4.2 on 2023-04-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.IntegerField(blank=True, default=0, verbose_name='Posição'),
        ),
    ]
