# Generated by Django 4.1.7 on 2023-04-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_category_id_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='texto',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
